<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EmployeesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Create admin user
        DB::table('employees')->insert([
            'user_id' => 1, 
            'department' => 'Administration', 
            'profile_image' => '', 
            'casual_leave' => 0, 
            'sick_leave' => 0, 
            'emergency_leave' => 0, 
            'pre_annual_emergency_leave' => 0, 
            'emergency_deduction_applied' => 0, 
            'study_leave' => 0, 
            'maternity_leave' => 0, 
            'paternity_leave' => 0, 
            'annual_leave' => 0, 
            'annual_leave_runs_count' => 0, 
            'annual_leave_history' => NULL, 
            'without_pay_leave' => 0, 
            'total_leave' => 0, 
            'leave_year' => 2026, 
            'hire_date' => '2023-10-01', 
            'status' => 'active', 
            'created_at' => now(), 
            'updated_at' => now(),
        ]);

        // Create test employees
        $testEmployees = [
            [
                'user_id' => 2, 
                'department' => 'Administration', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2022-05-01', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 3, 
                'department' => 'BSO', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2024-04-01', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 4, 
                'department' => 'BSO', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2020-01-01', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 5, 
                'department' => 'BSO', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2025-01-20', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 6, 
                'department' => 'BSO', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2025-10-10', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 7, 
                'department' => 'Audit', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2026-01-15', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 8, 
                'department' => 'Audit', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2015-02-01', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 9, 
                'department' => 'Audit', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2019-06-01', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],
            [
                'user_id' => 10, 
                'department' => 'Audit', 
                'profile_image' => '', 
                'casual_leave' => 0, 
                'sick_leave' => 0, 
                'emergency_leave' => 0, 
                'pre_annual_emergency_leave' => 0, 
                'emergency_deduction_applied' => 0, 
                'study_leave' => 0, 
                'maternity_leave' => 0, 
                'paternity_leave' => 0, 
                'annual_leave' => 0, 
                'annual_leave_runs_count' => 0, 
                'annual_leave_history' => NULL, 
                'without_pay_leave' => 0, 
                'total_leave' => 0, 
                'leave_year' => 2026, 
                'hire_date' => '2018-04-15', 
                'status' => 'active', 
                'created_at' => now(), 
                'updated_at' => now(),
            ],

        ];

        DB::table('employees')->insert($testEmployees);
    }
}
